### PR TITLE
Person on board load times

### PR DESCRIPTION
**Pull request by bardlokas**
Fix to load times
fix to pax/crew tables not listing

### CODE REVIEW

**Comment by kenlie-browne** [comment]
Viewing the draft port call caused the bowser tab to crash.
There are three calls to personOnBoard that are generating a few hundred megabytes of data each.

See screenshots for details.

screen shot 2018-11-27 at 10 03 22 pm

screen shot 2018-11-27 at 10 07 06 pm

The error occurs when viewing the first item in the draft list with the ship name '**Nordstjernen**'

**Comment by bardlokas** [comment]
This error should've been fixed by this, looking into it some more. I must've missed a commit or something. Thanks for checking

**Comment by bardlokas** [comment]
Added more changes

**Comment by kenlie-browne** [comment]
There is one more api call which is generating large amounts of data:
**portcall/overview/365** see attached screenshot for details.

screen shot 2018-11-28 at 9 02 58 am

**Comment by bardlokas** [comment]
> There is one more api call which is generating large amounts of data:
> **portcall/overview/365** see attached screenshot for details.
> 
> screen shot 2018-11-28 at 9 02 58 am

This is a part of this pull request and is it's own separate issue for another task.

**Pull request merged**
